# Copyright 2020 The inspec-gke-cis-benchmark Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: inspec-gke-cis-gcp
title: "InSpec GKE CIS 1.1 Benchmark"
maintainer: 
copyright: Google
copyright_email: copyright@google.com
license: Apache-2.0
summary: "Inspec Google Kubernetes Engine Center for Internet Security Benchmark v1.1 Profile"
version: "0.1.0"
supports:
- platform: gcp
depends:
- name: inspec-gcp-helpers
  url: https://github.com/GoogleCloudPlatform/inspec-gcp-helpers/archive/v1.0.7.tar.gz
inputs:
- name: gcp_project_id
  description: 'The GCP project identifier.'
  type: string
  value: "replace_with_your_gcp_project_id"
- name: cis_version
  description: 'The short version of the GKE CIS Benchmark'
  value: '1.1'
  type: string
- name: cis_url
  description: 'The URL to the GKE CIS Benchmark'
  value: 'https://www.cisecurity.org/benchmark/kubernetes/'
  type: string
- name: gcp_gke_locations
  description: 'The list of regions and/or zone names where GKE clusters are running. An empty array searches all locations'
  type: array
  value:
    - ""
- name: gce_zones
  description: 'The list of zone names where GCE instances are running. An empty array searches all locations'
  type: array
  value:
    - ""
- name: registry_storage_admin_list
  description: 'The allowed list of Storage Admins on Registry image bucket'
  type: array
  value:
    - ""
#   - "serviceAccount:test1@myproject.iam.gserviceaccount.com"
#   - "serviceAccount:test2@myproject.iam.gserviceaccount.com"
- name: registry_storage_object_admin_list
  description: 'The allowed list of Storage Object Admins on Registry image bucket'
  type: array
  value:
    - ""
#   - "serviceAccount:test1@myproject.iam.gserviceaccount.com"
#   - "serviceAccount:test2@myproject.iam.gserviceaccount.com"
- name: registry_storage_object_creator_list
  description: 'The allowed list of Storage Object Creators on Registry image bucket'
  type: array
  value:
    - ""
#   - "serviceAccount:test1@myproject.iam.gserviceaccount.com"
#   - "serviceAccount:test2@myproject.iam.gserviceaccount.com"
- name: registry_storage_legacy_bucket_owner_list
  description: 'The allowed list of Storage Legacy Bucket Owners on Registry image bucket'
  type: array
  value:
    - ""
#   - "projectEditor:pci-cis-good"
#   - "projectOwner:pci-cis-good"
#   - "serviceAccount:test1@myproject.iam.gserviceaccount.com"
#   - "serviceAccount:test2@myproject.iam.gserviceaccount.com"
- name: registry_storage_legacy_bucket_writer_list
  description: 'The allowed list of Storage Legacy Bucket Writers on Registry image bucket'
  type: array
  value:
    - ""
#   - "serviceAccount:test1@myproject.iam.gserviceaccount.com"
#   - "serviceAccount:test2@myproject.iam.gserviceaccount.com"
- name: registry_storage_legacy_object_owner_list
  description: 'The allowed list of Storage Legacy Object Owners on Registry image bucket'
  type: array
  value:
    - ""
#   - "serviceAccount:test1@myproject.iam.gserviceaccount.com"
#   - "serviceAccount:test2@myproject.iam.gserviceaccount.com"
